/**
 * Set the live savings password. Takes it as an argument so it never lands in a
 * file, hashes it locally, and writes only the hash to the database, which the
 * deployed site reads immediately. No Vercel variable, no redeploy.
 *
 *   npx tsx scripts/set-password.ts 'your password'
 */
import { hashPassword, setPasswordHash } from "../src/lib/savings/password";

const pw = process.argv[2];
if (!pw) {
  console.error("usage: npx tsx scripts/set-password.ts '<your password>'");
  console.error("(put the password in quotes; do not edit this file)");
  process.exit(1);
}
if (pw.length < 8) {
  console.error("Use at least 8 characters.");
  process.exit(1);
}

setPasswordHash(hashPassword(pw))
  .then(() => console.log("Password set. It works on the live site straight away."))
  .catch((err) => {
    console.error("Failed:", err);
    process.exit(1);
  });
